# Generated by Django 6.1 on 2026-08-28 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_prodi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BiodataGuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=50, unique=True)),
                ('jantina', models.CharField(choices=[('Lelaki', 'Lelaki'), ('Perempuan', 'Perempuan')], max_length=15)),
                ('no_telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'guru'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=100)),
                ('tingkat', models.CharField(max_length=20)),
                ('guru', models.ForeignKey(limit_choices_to={'role': 'guru'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prodi')),
            ],
        ),
        migrations.CreateModel(
            name='Materi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('file_materi', models.FileField(blank=True, null=True, upload_to='materi/')),
                ('teks_materi', models.TextField(blank=True, null=True)),
                ('waktu_dibuat', models.DateTimeField(auto_now_add=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kelas')),
            ],
        ),
        migrations.CreateModel(
            name='BiodataMurid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=50, unique=True)),
                ('jantina', models.CharField(choices=[('Lelaki', 'Lelaki'), ('Perempuan', 'Perempuan')], max_length=15)),
                ('tarikh_lahir', models.DateField(blank=True, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'murid'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prodi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.prodi')),
            ],
        ),
        migrations.CreateModel(
            name='SesiAbsensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_mulai', models.DateTimeField()),
                ('waktu_selesai', models.DateTimeField()),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kelas')),
            ],
        ),
        migrations.CreateModel(
            name='KehadiranMurid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_absen', models.DateTimeField(auto_now_add=True)),
                ('murid', models.ForeignKey(limit_choices_to={'role': 'murid'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sesi_absensi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sesiabsensi')),
            ],
        ),
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_tugas', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kelas')),
            ],
        ),
        migrations.CreateModel(
            name='PengumpulanTugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hasil', models.FileField(upload_to='tugas_hasil/')),
                ('waktu_submit', models.DateTimeField(auto_now_add=True)),
                ('nilai', models.IntegerField(blank=True, null=True)),
                ('murid', models.ForeignKey(limit_choices_to={'role': 'murid'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tugas')),
            ],
        ),
    ]
