# Generated by Django 6.1 on 2026-08-31 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_prodi_biodataguru_kelas_materi_biodatamurid_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='biodataguru',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'guru'}, on_delete=django.db.models.deletion.CASCADE, related_name='biodata_guru', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='biodatamurid',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'murid'}, on_delete=django.db.models.deletion.CASCADE, related_name='biodata_murid', to=settings.AUTH_USER_MODEL),
        ),
    ]
